ajust for news features

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -15,11 +15,40 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Show current directory and list files
+      - name: Run a one-line script
+        run: echo Hello, world!
+
+  get-the-files:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      
+      - name: Running a custom script
         run: |
-          echo "Current directory: $(pwd)"
-          echo "Contents of the current directory:"
           ls -al
+
+  get-the-multilinetask:
+    needs: 
+      - build
+      - get-the-files
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Run a multi-line script
+        if: always()
+        run: |
+          echo Add other actions to build,
+          echo test, and deploy your project.
+
+      - name: Check Java Version
+        run: |
+          java -version
 
       - name: Install Gradle
         run: |
@@ -30,8 +59,9 @@ jobs:
         run: |
           gradle build
 
-      - name: Verificar arquivos gerados pelo Gradle
+      - name: Verify files generated by Gradle
         run: |
+          echo "Checking contents of build/libs after Gradle build"
           ls -al build/libs
 
       - name: Docker version
@@ -42,6 +72,15 @@ jobs:
       - name: Docker Login
         run: echo "${{ secrets.dockerhubpassword }}" | docker login -u ${{ secrets.dockerhubusername }} --password-stdin
 
+      - name: Verify Dockerfile location
+        run: |
+          if [ -f ./Dockerfile ]; then
+            echo "Dockerfile found in the root directory."
+          else
+            echo "Dockerfile not found in the root directory."
+            exit 1
+          fi
+          
       - name: Docker image Tag
         env:
           IMAGE_TAG: ${{ github.sha }}
